Traceback (most recent call last):
  File "/Users/matthias/code/matters.global/websocket_server.py", line 14, in <module>
    from assistant_manager import AssistantManager
  File "/Users/matthias/code/matters.global/assistant_manager.py", line 15, in <module>
    from assistant_functions import (
  File "/Users/matthias/code/matters.global/assistant_functions.py", line 20, in <module>
    from graph_problem_manager import GraphManager, Matter, Goal, Problem, Condition, Solution, MatterLabel, ProblemState, SolutionState
  File "/Users/matthias/code/matters.global/graph_problem_manager.py", line 68, in <module>
    class Matter(BaseModel):
  File "/Users/matthias/code/matters.global/graph_problem_manager.py", line 111, in Matter
    def ensure_matter_label(cls, values: Dict[str, Any]) -> Dict[str, Any]:
  File "/opt/anaconda3/envs/mattersglobal/lib/python3.9/site-packages/pydantic/deprecated/class_validators.py", line 234, in root_validator
    return root_validator()(*__args)  # type: ignore
  File "/opt/anaconda3/envs/mattersglobal/lib/python3.9/site-packages/pydantic/deprecated/class_validators.py", line 240, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.11/u/root-validator-pre-skip
